from datetime import datetime
from typing import Any

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, UTCDateTime, utcnow

MESSAGE_TYPES = ("text", "system")


class Message(Base):
    __tablename__ = "messages"
    __table_args__ = (
        CheckConstraint(f"type IN {MESSAGE_TYPES}", name="type"),
        Index("ix_messages_conversation_id_id", "conversation_id", "id"),
        Index("ix_messages_expires_at", "expires_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    conversation_id: Mapped[int] = mapped_column(ForeignKey("conversations.id", ondelete="CASCADE"))
    sender_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    # Generated by the sending client; makes retries idempotent and matches the ack to the
    # optimistic bubble.
    client_id: Mapped[str | None] = mapped_column(String(64), unique=True)
    type: Mapped[str] = mapped_column(String(8), default="text")
    body: Mapped[str] = mapped_column(Text, default="")
    # Structured payload for system messages, e.g. {"event": "member_added", "targets": [3]}.
    meta: Mapped[dict[str, Any] | None] = mapped_column(JSON)
    reply_to_id: Mapped[int | None] = mapped_column(ForeignKey("messages.id", ondelete="SET NULL"))
    is_forwarded: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    edited_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    deleted_at: Mapped[datetime | None] = mapped_column(UTCDateTime)

    # Disappearing messages: the timer is copied from the conversation when the message is
    # sent and starts on first read, as in Signal.
    expires_in_seconds: Mapped[int | None] = mapped_column(Integer)
    expires_at: Mapped[datetime | None] = mapped_column(UTCDateTime)

    attachments: Mapped[list["Attachment"]] = relationship(
        back_populates="message", order_by="Attachment.id"
    )
    reactions: Mapped[list["Reaction"]] = relationship(cascade="all, delete-orphan")
    mentions: Mapped[list["MessageMention"]] = relationship(cascade="all, delete-orphan")
    receipts: Mapped[list["MessageReceipt"]] = relationship(cascade="all, delete-orphan")
    reply_to: Mapped["Message | None"] = relationship(remote_side="Message.id")


class MessageReceipt(Base):
    """One row per (message, recipient). The sender has no row."""

    __tablename__ = "message_receipts"
    __table_args__ = (Index("ix_message_receipts_user_id_read_at", "user_id", "read_at"),)

    message_id: Mapped[int] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), primary_key=True
    )
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    delivered_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    read_at: Mapped[datetime | None] = mapped_column(UTCDateTime)


class MessageHidden(Base):
    """'Delete for me': the message stays for everyone else."""

    __tablename__ = "message_hidden"

    message_id: Mapped[int] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), primary_key=True
    )
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )


class MessageMention(Base):
    __tablename__ = "message_mentions"

    message_id: Mapped[int] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), primary_key=True
    )
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )


class Reaction(Base):
    """Signal allows one reaction per person per message; a new emoji replaces the old one."""

    __tablename__ = "reactions"

    message_id: Mapped[int] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), primary_key=True
    )
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    emoji: Mapped[str] = mapped_column(String(16))
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)


class Attachment(Base):
    """Uploaded before the message exists, then linked when the message is sent."""

    __tablename__ = "attachments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    message_id: Mapped[int | None] = mapped_column(
        ForeignKey("messages.id", ondelete="CASCADE"), index=True
    )
    uploader_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    kind: Mapped[str] = mapped_column(String(8))  # image | video | audio | voice | file
    file_name: Mapped[str] = mapped_column(String(255))
    mime_type: Mapped[str] = mapped_column(String(127))
    size_bytes: Mapped[int] = mapped_column(BigInteger)
    width: Mapped[int | None] = mapped_column(Integer)
    height: Mapped[int | None] = mapped_column(Integer)
    duration_ms: Mapped[int | None] = mapped_column(Integer)
    # Not unique: forwarding copies the row but shares the stored file.
    storage_key: Mapped[str] = mapped_column(String(255), index=True)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)

    message: Mapped[Message | None] = relationship(back_populates="attachments")
