import { randomBytes } from "node:crypto";
import dgram from "node:dgram";
import fs from "node:fs";
import net from "node:net";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Generate a scoped, authenticated relay configuration without exposing its
// credential in terminal output. Files stay outside version control.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const runtime = path.join(root, "turn", ".runtime");
const args = process.argv.slice(2);
const options = {};
for (let i = 0; i < args.length; i++) {
  const option = args[i];
  if (option === "--configure-app") options.configureApp = true;
  else if (["--public-ip", "--host"].includes(option) && args[i + 1] && !args[i + 1].startsWith("--")) {
    options[option.slice(2)] = args[++i];
  } else throw new Error("Usage: node scripts/setup-turn.mjs [--public-ip IPv4] [--host hostname] [--configure-app]");
}

async function localAddress() {
  // Connect chooses the outbound interface; no UDP packet is sent.
  const socket = dgram.createSocket("udp4");
  try {
    await new Promise((resolve, reject) => {
      socket.once("error", reject);
      socket.connect(9, "8.8.8.8", resolve);
    });
    return socket.address().address;
  } finally { socket.close(); }
}

function writePrivate(file, text) {
  fs.writeFileSync(file, text, { encoding: "utf8", mode: 0o600 });
  // An existing file may have different permissions. On Windows use the normal
  // checkout ACL; on POSIX keep the credential files owner-readable only.
  if (process.platform !== "win32") fs.chmodSync(file, 0o600);
}

function updateEnv(file, value) {
  const previous = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
  const lines = previous.split(/\r?\n/);
  const setting = `NEXT_PUBLIC_RTC_ICE_SERVERS=${value}`;
  let replaced = false;
  const next = lines.flatMap((line) => {
    if (!/^\s*NEXT_PUBLIC_RTC_ICE_SERVERS\s*=/.test(line)) return [line];
    if (replaced) return [];
    replaced = true;
    return [setting];
  });
  if (!replaced) next.push(setting);
  writePrivate(file, `${next.join("\n").trimEnd()}\n`);
}

fs.mkdirSync(runtime, { recursive: true });
const stateFile = path.join(runtime, "settings.json");
const previous = fs.existsSync(stateFile) ? JSON.parse(fs.readFileSync(stateFile, "utf8")) : {};
const publicIP = options["public-ip"] ?? previous.publicIP ?? await localAddress();
const host = options.host ?? (options["public-ip"] ? publicIP : previous.host ?? publicIP);
if (net.isIP(publicIP) !== 4 || publicIP.startsWith("127.") || publicIP === "0.0.0.0" || Number(publicIP.split(".")[0]) >= 224) {
  throw new Error("--public-ip must be a reachable, unicast IPv4 address (not loopback). For local testing use your LAN IPv4.");
}
if (!/^[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?$/.test(host) || host.length > 253) {
  throw new Error("--host must be an IPv4 address or DNS hostname without scheme or port.");
}
const username = "signal-clone";
const credential = previous.credential ?? randomBytes(32).toString("hex");
if (!/^[a-f0-9]{64}$/.test(credential)) throw new Error("Invalid existing TURN credential; check turn/.runtime/settings.json.");
const ice = JSON.stringify([
  { urls: "stun:stun.l.google.com:19302" },
  { urls: "stun:stun1.l.google.com:19302" },
  { urls: [`turn:${host}:3478?transport=udp`, `turn:${host}:3478?transport=tcp`], username, credential },
]);
const config = [
  "# Generated by scripts/setup-turn.mjs; contains a private credential.",
  // Let Coturn discover its concrete container interfaces. A wildcard listener
  // can map the advertised relay address back to 0.0.0.0 for peer permissions.
  "listening-port=3478", `external-ip=${publicIP}`,
  "min-port=49160", "max-port=49200", "relay-threads=2", "fingerprint",
  "lt-cred-mech", "realm=signal-clone", `user=${username}:${credential}`,
  "user-quota=16", "total-quota=32", "max-bps=1500000", "bps-capacity=20000000",
  "no-tls", "no-tcp-relay", "no-multicast-peers",
  "denied-peer-ip=169.254.0.0-169.254.255.255",
  "pidfile=/tmp/turnserver.pid", "userdb=/tmp/turndb", "log-file=stdout", "simple-log",
].join("\n");
writePrivate(stateFile, `${JSON.stringify({ publicIP, host, credential }, null, 2)}\n`);
writePrivate(path.join(runtime, "turnserver.conf"), `${config}\n`);
writePrivate(path.join(runtime, "frontend.env"), `NEXT_PUBLIC_RTC_ICE_SERVERS=${ice}\n`);
// Coturn's unprivileged container user must read this mounted file. The settings
// and frontend.env remain owner-only; the checkout directory controls access.
if (process.platform !== "win32") fs.chmodSync(path.join(runtime, "turnserver.conf"), 0o644);
if (options.configureApp) {
  updateEnv(path.join(root, "frontend", ".env.local"), ice);
  updateEnv(path.join(root, ".env"), ice);
}
console.log(`TURN configuration prepared for ${host}:3478 (advertised relay IPv4 ${publicIP}).`);
console.log("Credential retained/generated in ignored turn/.runtime files; no credential is printed.");
if (options.configureApp) console.log("Updated only the ICE setting in frontend/.env.local and root .env. Rebuild the frontend to apply it.");
console.log("Start: docker compose -f turn/compose.yaml up -d --wait");
